
#define DOCUMENTS_UNARCHIVER    0
#define XFOLDER_UNARCHIVER      1
#define INBOX_UNARCHIVER        2
#define DROPBOX_UNARCHIVER      3
#define YANDEX_UNARCHIVER       4
#define GOOGLE_UNARCHIVER       5
#define BOX_UNARCHIVER          6
#define HOME_SEC_0_ROW_COUNT    7

#define CAMERA_UNARCHIVER       0
#define HOME_SEC_1_ROW_COUNT    1